import { readFile, writeFile } from "node:fs/promises";
import { build } from "esbuild";
import { SpinEsbuildPlugin } from "@spinframework/build-tools/plugins/esbuild";

const client = await build({
  entryPoints: ["src/client.ts"],
  bundle: true,
  format: "esm",
  write: false,
  minify: true,
});
await build({
  entryPoints: ["src/index.ts"],
  outfile: "build/component.js",
  bundle: true,
  format: "esm",
  platform: "browser",
  define: {
    CLIENT_SCRIPT: JSON.stringify(client.outputFiles[0].text),
    STYLES: JSON.stringify(await readFile("src/style.css", "utf8")),
    PAGE: JSON.stringify(await readFile("src/page.html", "utf8")),
  },
  plugins: [
    await SpinEsbuildPlugin({ componentize: { output: "dist/viewer.wasm" } }),
  ],
});

const manifest = await readFile("../spin.toml", "utf8");
await writeFile(
  "../spin.viewer.toml",
  manifest +
    `
# Generated by viewer/build.mjs; rebuild after changing spin.toml.
[[trigger.http]]
route = "/browse"
component = "viewer"

[[trigger.http]]
route = "/browse/assets/client.js"
component = "viewer"

[[trigger.http]]
route = "/browse/assets/style.css"
component = "viewer"

[component.viewer]
source = "viewer/dist/viewer.wasm"
allowed_outbound_hosts = []
`,
);
