spin_manifest_version = 2
[application]
name = "wal-git"
version = "0.0.0"

[variables]
wal_endpoint = { default = "http://127.0.0.1:19090" }
wal_bucket = { default = "wal-proof" }
wal_region = { default = "us-east-1" }

[[trigger.http]]
route = "/..."
component = "git"

[component.git]
source = "git.wasm"
allowed_outbound_hosts = ["{{ wal_endpoint }}"]
[component.git.environment]
WAL_ENDPOINT = "{{ wal_endpoint }}"
WAL_BUCKET = "{{ wal_bucket }}"
WAL_REGION = "{{ wal_region }}"
